baseURL = "/"
languageCode = "en-us"
title = "AOSCD"
Paginate = 1000
googleAnalytics = ""
theme = "showcase-hugo-theme"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  author = "Alternativas Open Source para la Ciencia de Datos (AOSCD)"
  description = "Alternativas Open Source para la Ciencia de Datos"
  message = "AOSCD es un proyecto que pretende ofrecer alternativas Open Source al uso de software privativo para la solución de tareas específicas en la ciencia de datos. A continuación, encontrarás un listado de todos los recursos que hemos creado y se encuentran a a su completa disposición disposición."
  hideAutoMenu = false

[social]
  twitter = "https://twitter.com/search?q=%23aoscd&src=typed_query"
  github = "https://github.com/aoscd"
